id: A211C5CE0
title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils All
  Wishes
type: translation
pechas:
- I2F9B969B
- IDAADA5D1
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:09.279093
  last_modified_at: 2023-01-04 11:51:09.279106
  collections:
  - Dzongter Kunzang Nyima
  - Works of Tibetan Masters
alignment_to_base:
  I2F9B969B/9E0A: 94F7
  IDAADA5D1/0F76: 94F7
